-- V1: 共通基盤（Employee 土台）
-- 担当: 共通基盤フェーズ（王・代表1台）。A/B/C はこの employee(id) を参照する。
-- 方針: H2/PostgreSQL 両対応を意識し標準寄りの型で書く（将来 PG 移行のため）。

CREATE TABLE employee (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,           -- BCrypt ハッシュ（平文保存禁止）
    role          VARCHAR(20)  NOT NULL,           -- ADMIN / MEMBER（共有 Enum: Role）
    version       BIGINT       NOT NULL DEFAULT 0, -- 楽観ロック（@Version）
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employee_email UNIQUE (email)    -- email はログイン ID 兼用。重複はエラー(409)
);

-- 連番の予約（IF 先行合意）: V1=共通基盤 / V2=Unit A / V3=Unit B / V4=Unit C
-- 各 Unit は自分の番号でテーブルを追加し、連番衝突を避ける。
